### ISSUE TITLE
Gateway functionality and rest api

### ISSUE THREAD

**Issue by nkaramolegos** [hyperledgendary/fabric-rest-sample#50]
Hello, I am bit confused. Does the client application is initialized [here](https://github.com/hyperledgendary/fabric-rest-sample/blob/568fd0f436136e4d6598a76da8e8a30cac07843d/asset-transfer-basic/rest-api-typescript/src/index.ts)? If yes, how the gateway functionality runs always without stopping in order to support the REST calls which can occur at any time?

Also, in the fabric samples there is a [function](https://github.com/hyperledger/fabric-samples/blob/271dfbb9bcde2d29b8b05190749111f31916bbb5/asset-transfer-basic/application-gateway-typescript/src/app.ts#L110) which returns all the assets on the ledger. In this case, how the REST server knows which function to use for the resource api/assets

Excuse my ignorance but I am new to REST APIs

**Comment by jt-nti** [comment]
Hi @nkaramolegos, thanks for the questions- I'm trying to collect feedback on the REST sample before adding it to the main fabric-samples repo, so they're really helpful to get an idea of how easy the code is to follow.

Yes, the client is initialized in index.ts and actually two gateway connections are created- one for each organization. One thing that I think needs clarifying is that REST calls that submit a transaction are handled differently to REST calls that evaluate transactions. Transactions are submitted using a job queue, and the gateway connections are passed to the job queue worker https://github.com/hyperledgendary/fabric-rest-sample/blob/main/asset-transfer-basic/rest-api-typescript/src/index.ts#L60 whereas transactions are evaluated without using the queue, and the gateway connections are added to the app where they can be retrieved from when processing REST calls https://github.com/hyperledgendary/fabric-rest-sample/blob/main/asset-transfer-basic/rest-api-typescript/src/index.ts#L68

Let me know if you have any ideas about how that could be made more obvious in the code, or if I still haven't explained it very well.

assets.router.ts has the code to handle get all assets which is just hard coded here https://github.com/hyperledgendary/fabric-rest-sample/blob/main/asset-transfer-basic/rest-api-typescript/src/assets.router.ts#L43 (It's possible to use contract metadata to automatically adapt to the transactions available in a contract, however I wanted to keep the sample as simple as possible, so they're hard coded to match the basic asset contract.)

I hope that helps. Let me know if you have any other questions or suggestions.

**Comment by nkaramolegos** [comment]
I think that you are very clear. Thus, lets say that I want to use this fabric-rest server for an other chaincode in an other channel (where my orgs belong) what should I change? Also, I have seen that the k8s [example](https://github.com/hyperledger/fabric-samples/blob/main/test-network-k8s/docs/APPLICATIONS.md) uses this repository, are you aware of where the REST server is running? Is it inside the kubernetes? Finally, where can I define the identities of the user (wallet) of the gateway application that is initialized in index.ts?
Thank you very much

**Comment by jt-nti** [comment]
The identities, orgs, channel name, and chaincode name can all be configured via environment variables https://github.com/hyperledgendary/fabric-rest-sample/blob/main/asset-transfer-basic/rest-api-typescript/src/config.ts#L104 (making that more obvious is something people have mentioned before :)

If you wanted to use this sample with another chaincode, i.e. not the basic asset sample, you would need to start adapting the code. Use the assets.router.ts as an example and create endpoints which make sense for your transactions.

If you're interested in the option of using the contract metadata instead of writing the REST API by hand, you might be able to get some ideas from the [fabric-rest-server](https://github.com/hyperledgendary/fabric-rest-server) but I'm not sure what state that is in.

As far as I know [the k8s sample does run the REST server as a deployment in kubernetes](https://github.com/hyperledger/fabric-samples/blob/main/test-network-k8s/kube/fabric-rest-sample.yaml)

**Comment by nkaramolegos** [comment]
You are the best. 

Let me give you more details about the idea I want to implement. I will have M orgs which will belong to channelA and use chaincodeA. If a request occur I will deploy a new channelB with the chaincodeB and I will add these M orgs. 

I would like to base my implementation to fabric-rest-sample in order to use one client application operated my userA (belonging to org1, does not matter) with multiple identities (i.e ID1, ID2, etc) as shown [here](https://hyperledger-fabric.readthedocs.io/fa/latest/developapps/wallet.html). Thus this userA can have access to channelA with ID1 and channelB with ID2. The type of transactions will be the same for each chaincode (e.g ReadAsset, WriteAsset) so the assets.router.ts file does not need many changes as I understand. 

Can I on the fly use different IDs and channels while the rest server is running? Of course, I will change the rest endpoints in order to get the information needed for the desired ID and channel (instead of using the ENVs) and use them as gateway parameters to connect to the corresponding channel. Is this possible?

**Comment by jt-nti** [comment]
I think there are different ways you could approach that depending on what you're happy trusting, and how often you add users and new channels. If things are fairly static you could keep the approach of configuring identities and channels via environment variables. If not, you might want to introduce a wallet/identity store (perhaps using an HSM) and configure the REST server to use that. Alternatively you could include the identities in the actual REST calls so that the REST server doesn't hold them at all or, extending that further, investigate the possibility of offline signing where the REST server doesn't need the identities at all.

The REST sample intentionally very simplistic because the goal was mainly to demonstrate that you shouldn't create a new gateway connection for every transaction, so there would be a bit of work involved which ever approach you choose.

**Comment by nkaramolegos** [comment]
Therefore, the REST sample establish a connection to predefined channel(s) and keep it open to support all the incoming calls. The truth is that my network will not be static. The channels and the chaincodes will be update at least once a week (I may use either the SDK or the bash scripts for that). Meanwhile, I am looking for the best way to extend the REST sample for supporting multiple channels on the fly combined with the official k8s-sample. Your ideas are good. Most likely, I will modify the REST calls to include the information of the desired channel (and thus the appropriate chaincode) so that the REST server to use the this information and the gateway functionality to connect to the correct channel. Of course this means that each time a new request occurs I would have to establish a new connection, unfortunately this may add latency or is against the common approach but I can not think something else in order to support the on the fly logic (an the other way may be to update the config ENVs file each time :( ). Regarding, the different IDs (one for each channel as [Isabella](https://hyperledger-fabric.readthedocs.io/en/release-2.2/developapps/wallet.html)) of the single user of the client application I have to think about it (I may included this to REST calls too)

Any proposals are important. Thank you for the solid work.

**Comment by nkaramolegos** [comment]
One more question. How the rest calls are served? Synchronous or asynchronous?

**Comment by jt-nti** [comment]
Hi @nkaramolegos 

> The channels and the chaincodes will be updated at least once a week

You could add a "channels" endpoint to the REST server, or something similar, so that it can be updated more easily when your network changes. If you do decide to include the channel information in all REST calls, it would still be preferable to reuse any existing connection rather than always establishing a connection per call.

> One more question. How the rest calls are served? Synchronous or asynchronous?

The query transactions, e.g. when getting an asset, come back synchronously, whereas any submit transactions, e.g. when creating a new asset, are queued for processing asynchronously.

I'll try and gather a bit more feedback to see if it's worth updating the sample to make channels more dynamic, or whether that's too much complexity for a basic scenario. Thanks very much for the feedback so far and let me know if you have more questions.

**Comment by nkaramolegos** [comment]
@jt-nti I have to thank you for your ideas and help. I understand the second part but (unfortunately) I do not understand the first part. What will I gain with the channel endpoint? Do you mean to use it for updating some channel list and then the application to use this list via the GW? If the channels are updated I understand that I have to open a new client connection to fabric network (for the new channel). How can I reuse this connection in more than one calls?

**Comment by jt-nti** [comment]
Hi @nkaramolegos,
> Do you mean to use it for updating some channel list and then the application to use this list via the GW?
So I think you would need to store the connection details in a database somewhere and either manage them by updating the database directly, or exposing an additional endpoint on the REST server. Similarly for any user credentials. The REST server would either need to poll for changes, or subscribe to updates, to create new connections when they get added. The sample just uses the express `app.set` to make contracts available for reuse. I'm not 100% sure that's how it's meant to be used but it seems to work.

**Comment by jt-nti** [comment]
> The sample just uses the express app.set to make contracts available for reuse. I'm not 100% sure that's how it's meant to be used but it seems to work.

In case it helps, I switched using app.locals in #57

**Comment by jt-nti** [comment]
I'm hoping to archive this repository once PR hyperledger/fabric-samples#510 is merged. If you have more questions about the REST sample after that, it looks like the [fabric-samples repo has discussions enabled](https://github.com/hyperledger/fabric-samples/discussions)

**Comment by nkaramolegos** [comment]
You have made a lot of effort to help me. Thank you. However, I am still confused (I really hope to be the last question). Let's start again. In the current implementation you have only one channel. So you have stored using the app.local the userA ID1 credentials for connecting to this channel. Once you connect to this channel (using the GW functionality) you keep the connection open for future transactions. Correct?

Now in a case a new channel is added I have to connect to this channel using the userA ID2. In this case I can follow one of the following two solutions:
1) To change the rest call content in order to have the credentials for each ID of the user
2) Keep to my client application the wallet(s) with the credentials and extend the rest call content to have information for the target channel (and thus to use the correct wallet ID)

Regardless of the way I choose, I would like to keep the connection open once is established for a channel in order to avoid connecting again each time. However, I don't understand how the app.locals logic will help me.

**Comment by jt-nti** [comment]
> In the current implementation you have only one channel. So you have stored using the app.local the userA ID1 credentials for connecting to this channel. Once you connect to this channel (using the GW functionality) you keep the connection open for future transactions. Correct?

Essentially, yes, although for two IDs -> https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-basic/rest-api-typescript/src/index.ts#L67

> Now in a case a new channel is added ... I can follow one of the following two solutions:

For the first solution, and avoid connecting every time, I think you should be able to add a function to get the contract from app.locals, and connect/store the contract on app.locals if it's not already there.

Where the current sample just gets the contract in the routers, you'd use your new function, e.g. here -> https://github.com/hyperledger/fabric-samples/blob/main/asset-transfer-basic/rest-api-typescript/src/assets.router.ts#L123

I'm not sure I completely follow the second solution but I think I would probably do it slightly differently and have the REST server app subscribe to a channel updates topic and add new connections to apps.local when new channel details get published. BullMQ doesn't handle that scenario but that just sits on top of Redis which does support pubsub that should hopefully work https://redis.io/topics/pubsub (you'd need a way to publish the channel updates as well, either with a separate app or extending the REST server).

Hope that helps a bit. It's definitely an interesting scenario and might be worth an additional sample in fabric-samples if it's something more people are interested in. I'm about to archive this repository now that [the PR has been merged to fabric samples](https://github.com/hyperledger/fabric-samples/pull/510) but please use the [fabric-samples](https://github.com/hyperledger/fabric-samples) discussions if you have more questions, or even open an issue there for adding an extended REST sample to see how much interest there would be developing something more complex.
